'use client'

import { useState } from 'react'

// List of characters to display
const characterSets = {
  basicLatin: [
    { character: 'A', unicode: 'U+0041', title: 'LATIN CAPITAL LETTER A' },
    { character: 'B', unicode: 'U+0042', title: 'LATIN CAPITAL LETTER B' },
    { character: 'C', unicode: 'U+0043', title: 'LATIN CAPITAL LETTER C' },
    { character: 'D', unicode: 'U+0044', title: 'LATIN CAPITAL LETTER D' },
    { character: 'E', unicode: 'U+0045', title: 'LATIN CAPITAL LETTER E' },
    { character: 'F', unicode: 'U+0046', title: 'LATIN CAPITAL LETTER F' },
    { character: 'G', unicode: 'U+0047', title: 'LATIN CAPITAL LETTER G' },
    { character: 'H', unicode: 'U+0048', title: 'LATIN CAPITAL LETTER H' },
    { character: 'I', unicode: 'U+0049', title: 'LATIN CAPITAL LETTER I' },
    { character: 'J', unicode: 'U+004A', title: 'LATIN CAPITAL LETTER J' },
    { character: 'K', unicode: 'U+004B', title: 'LATIN CAPITAL LETTER K' },
    { character: 'L', unicode: 'U+004C', title: 'LATIN CAPITAL LETTER L' },
    { character: 'M', unicode: 'U+004D', title: 'LATIN CAPITAL LETTER M' },
    { character: 'N', unicode: 'U+004E', title: 'LATIN CAPITAL LETTER N' },
    { character: 'O', unicode: 'U+004F', title: 'LATIN CAPITAL LETTER O' },
    { character: 'P', unicode: 'U+0050', title: 'LATIN CAPITAL LETTER P' },
    { character: 'Q', unicode: 'U+0051', title: 'LATIN CAPITAL LETTER Q' },
    { character: 'R', unicode: 'U+0052', title: 'LATIN CAPITAL LETTER R' },
    { character: 'S', unicode: 'U+0053', title: 'LATIN CAPITAL LETTER S' },
    { character: 'T', unicode: 'U+0054', title: 'LATIN CAPITAL LETTER T' },
    { character: 'U', unicode: 'U+0055', title: 'LATIN CAPITAL LETTER U' },
    { character: 'V', unicode: 'U+0056', title: 'LATIN CAPITAL LETTER V' },
    { character: 'W', unicode: 'U+0057', title: 'LATIN CAPITAL LETTER W' },
    { character: 'X', unicode: 'U+0058', title: 'LATIN CAPITAL LETTER X' },
    { character: 'Y', unicode: 'U+0059', title: 'LATIN CAPITAL LETTER Y' },
    { character: 'Z', unicode: 'U+005A', title: 'LATIN CAPITAL LETTER Z' },
    { character: 'a', unicode: 'U+0061', title: 'LATIN SMALL LETTER A' },
    { character: 'b', unicode: 'U+0062', title: 'LATIN SMALL LETTER B' },
    { character: 'c', unicode: 'U+0063', title: 'LATIN SMALL LETTER C' },
    { character: 'd', unicode: 'U+0064', title: 'LATIN SMALL LETTER D' },
    { character: 'e', unicode: 'U+0065', title: 'LATIN SMALL LETTER E' },
    { character: 'f', unicode: 'U+0066', title: 'LATIN SMALL LETTER F' },
    { character: 'g', unicode: 'U+0067', title: 'LATIN SMALL LETTER G' },
    { character: 'h', unicode: 'U+0068', title: 'LATIN SMALL LETTER H' },
    { character: 'i', unicode: 'U+0069', title: 'LATIN SMALL LETTER I' },
    { character: 'j', unicode: 'U+006A', title: 'LATIN SMALL LETTER J' },
    { character: 'k', unicode: 'U+006B', title: 'LATIN SMALL LETTER K' },
    { character: 'l', unicode: 'U+006C', title: 'LATIN SMALL LETTER L' },
    { character: 'm', unicode: 'U+006D', title: 'LATIN SMALL LETTER M' },
    { character: 'n', unicode: 'U+006E', title: 'LATIN SMALL LETTER N' },
    { character: 'o', unicode: 'U+006F', title: 'LATIN SMALL LETTER O' },
    { character: 'p', unicode: 'U+0070', title: 'LATIN SMALL LETTER P' },
    { character: 'q', unicode: 'U+0071', title: 'LATIN SMALL LETTER Q' },
    { character: 'r', unicode: 'U+0072', title: 'LATIN SMALL LETTER R' },
    { character: 's', unicode: 'U+0073', title: 'LATIN SMALL LETTER S' },
    { character: 't', unicode: 'U+0074', title: 'LATIN SMALL LETTER T' },
    { character: 'u', unicode: 'U+0075', title: 'LATIN SMALL LETTER U' },
    { character: 'v', unicode: 'U+0076', title: 'LATIN SMALL LETTER V' },
    { character: 'w', unicode: 'U+0077', title: 'LATIN SMALL LETTER W' },
    { character: 'x', unicode: 'U+0078', title: 'LATIN SMALL LETTER X' },
    { character: 'y', unicode: 'U+0079', title: 'LATIN SMALL LETTER Y' },
    { character: 'z', unicode: 'U+007A', title: 'LATIN SMALL LETTER Z' },
  ],
  extendedLatin: [
    { character: 'Á', unicode: 'U+00C1', title: 'LATIN CAPITAL LETTER A WITH ACUTE' },
    { character: 'Ă', unicode: 'U+0102', title: 'LATIN CAPITAL LETTER A WITH BREVE' },
    // { character: 'Ǎ', unicode: 'U+01CD', title: 'LATIN CAPITAL LETTER A WITH CARON' },
    { character: 'Â', unicode: 'U+00C2', title: 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX' },
    { character: 'Ä', unicode: 'U+00C4', title: 'LATIN CAPITAL LETTER A WITH DIAERESIS' },
    { character: 'Ạ', unicode: 'U+1EA0', title: 'LATIN CAPITAL LETTER A WITH DOT BELOW' },
    { character: 'À', unicode: 'U+00C0', title: 'LATIN CAPITAL LETTER A WITH GRAVE' },
    { character: 'Ā', unicode: 'U+0100', title: 'LATIN CAPITAL LETTER A WITH MACRON' },
    { character: 'Ą', unicode: 'U+0104', title: 'LATIN CAPITAL LETTER A WITH OGONEK' },
    { character: 'Å', unicode: 'U+00C5', title: 'LATIN CAPITAL LETTER A WITH RING ABOVE' },
    {
      character: 'Ǻ',
      unicode: 'U+01FA',
      title: 'LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE',
    },
    { character: 'Ã', unicode: 'U+00C3', title: 'LATIN CAPITAL LETTER A WITH TILDE' },
    { character: 'Æ', unicode: 'U+00C6', title: 'LATIN CAPITAL LETTER AE' },
    { character: 'Ǽ', unicode: 'U+01FC', title: 'LATIN CAPITAL LETTER AE WITH ACUTE' },
    { character: 'Ḃ', unicode: 'U+1E02', title: 'LATIN CAPITAL LETTER B WITH DOT ABOVE' },
    { character: 'Ɓ', unicode: 'U+0181', title: 'LATIN CAPITAL LETTER B WITH HOOK' },
    { character: 'Ć', unicode: 'U+0106', title: 'LATIN CAPITAL LETTER C WITH ACUTE' },
    { character: 'Č', unicode: 'U+010C', title: 'LATIN CAPITAL LETTER C WITH CARON' },
    { character: 'Ç', unicode: 'U+00C7', title: 'LATIN CAPITAL LETTER C WITH CEDILLA' },
    { character: 'Ĉ', unicode: 'U+0108', title: 'LATIN CAPITAL LETTER C WITH CIRCUMFLEX' },
    { character: 'Ċ', unicode: 'U+010A', title: 'LATIN CAPITAL LETTER C WITH DOT ABOVE' },
    { character: 'Ď', unicode: 'U+010E', title: 'LATIN CAPITAL LETTER D WITH CARON' },
    { character: 'Ḑ', unicode: 'U+1E10', title: 'LATIN CAPITAL LETTER D WITH CEDILLA' },
    { character: 'Đ', unicode: 'U+0110', title: 'LATIN CAPITAL LETTER D WITH STROKE' },
    { character: 'Ḋ', unicode: 'U+1E0A', title: 'LATIN CAPITAL LETTER D WITH DOT ABOVE' },
    //{ character: 'Ḍ', unicode: 'U+1E0C', title: 'LATIN CAPITAL LETTER D WITH DOT BELOW' },
    { character: 'Ɗ', unicode: 'U+018A', title: 'LATIN CAPITAL LETTER D WITH HOOK' },
    // { character: 'Ɖ', unicode: 'U+0189', title: 'LATIN CAPITAL LETTER AFRICAN D' },
    { character: 'Ð', unicode: 'U+00D0', title: 'LATIN CAPITAL LETTER ETH' },
    { character: 'É', unicode: 'U+00C9', title: 'LATIN CAPITAL LETTER E WITH ACUTE' },
    { character: 'Ĕ', unicode: 'U+0114', title: 'LATIN CAPITAL LETTER E WITH BREVE' },
    { character: 'Ě', unicode: 'U+011A', title: 'LATIN CAPITAL LETTER E WITH CARON' },
    { character: 'Ê', unicode: 'U+00CA', title: 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX' },
    { character: 'Ë', unicode: 'U+00CB', title: 'LATIN CAPITAL LETTER E WITH DIAERESIS' },
    { character: 'Ė', unicode: 'U+0116', title: 'LATIN CAPITAL LETTER E WITH DOT ABOVE' },
    { character: 'Ẹ', unicode: 'U+1EB8', title: 'LATIN CAPITAL LETTER E WITH DOT BELOW' },
    { character: 'È', unicode: 'U+00C8', title: 'LATIN CAPITAL LETTER E WITH GRAVE' },
    { character: 'Ē', unicode: 'U+0112', title: 'LATIN CAPITAL LETTER E WITH MACRON' },
    { character: 'Ę', unicode: 'U+0118', title: 'LATIN CAPITAL LETTER E WITH OGONEK' },
    // { character: 'Ɛ', unicode: 'U+0190', title: 'LATIN CAPITAL LETTER OPEN E' },
    { character: 'Ẽ', unicode: 'U+1EBC', title: 'LATIN CAPITAL LETTER E WITH TILDE' },
    // { character: 'Ǝ', unicode: 'U+018E', title: 'LATIN CAPITAL LETTER REVERSED E' },
    { character: 'Ə', unicode: 'U+018F', title: 'LATIN CAPITAL LETTER SCHWA' },
    // { character: 'Ḟ', unicode: 'U+1E1E', title: 'LATIN CAPITAL LETTER F WITH DOT ABOVE' },
    // { character: 'Ƒ', unicode: 'U+0191', title: 'LATIN CAPITAL LETTER F WITH HOOK' },
    { character: 'Ğ', unicode: 'U+011E', title: 'LATIN CAPITAL LETTER G WITH BREVE' },
    { character: 'Ǧ', unicode: 'U+01E6', title: 'LATIN CAPITAL LETTER G WITH CARON' },
    { character: 'Ĝ', unicode: 'U+011C', title: 'LATIN CAPITAL LETTER G WITH CIRCUMFLEX' },
    { character: 'Ģ', unicode: 'U+0122', title: 'LATIN CAPITAL LETTER G WITH CEDILLA' },
    { character: 'Ġ', unicode: 'U+0120', title: 'LATIN CAPITAL LETTER G WITH DOT ABOVE' },
    // { character: 'Ɠ', unicode: 'U+0193', title: 'LATIN CAPITAL LETTER G WITH HOOK' },
    // { character: 'Ḡ', unicode: 'U+1E20', title: 'LATIN CAPITAL LETTER G WITH MACRON' },
    { character: 'Ħ', unicode: 'U+0126', title: 'LATIN CAPITAL LETTER H WITH STROKE' },
    // { character: 'Ḫ', unicode: 'U+1E2A', title: 'LATIN CAPITAL LETTER H WITH BREVE BELOW' },
    // { character: 'Ȟ', unicode: 'U+021E', title: 'LATIN CAPITAL LETTER H WITH CARON' },
    { character: 'Ĥ', unicode: 'U+0124', title: 'LATIN CAPITAL LETTER H WITH CIRCUMFLEX' },
    { character: 'Ḥ', unicode: 'U+1E24', title: 'LATIN CAPITAL LETTER H WITH DOT BELOW' },
    { character: 'Ĳ', unicode: 'U+0132', title: 'LATIN CAPITAL LIGATURE IJ' },
    { character: 'Í', unicode: 'U+00CD', title: 'LATIN CAPITAL LETTER I WITH ACUTE' },
    { character: 'Ĭ', unicode: 'U+012C', title: 'LATIN CAPITAL LETTER I WITH BREVE' },
    { character: 'Ǐ', unicode: 'U+01CF', title: 'LATIN CAPITAL LETTER I WITH CARON' },
    { character: 'Î', unicode: 'U+00CE', title: 'LATIN CAPITAL LETTER I WITH CIRCUMFLEX' },
    { character: 'Ï', unicode: 'U+00CF', title: 'LATIN CAPITAL LETTER I WITH DIAERESIS' },
    { character: 'İ', unicode: 'U+0130', title: 'LATIN CAPITAL LETTER I WITH DOT ABOVE' },
    { character: 'Ị', unicode: 'U+1ECA', title: 'LATIN CAPITAL LETTER I WITH DOT BELOW' },
    { character: 'Ì', unicode: 'U+00CC', title: 'LATIN CAPITAL LETTER I WITH GRAVE' },
    { character: 'Ī', unicode: 'U+012A', title: 'LATIN CAPITAL LETTER I WITH MACRON' },
    { character: 'Į', unicode: 'U+012E', title: 'LATIN CAPITAL LETTER I WITH OGONEK' },
    // { character: 'Ɨ', unicode: 'U+0197', title: 'LATIN CAPITAL LETTER I WITH STROKE' },
    { character: 'Ĩ', unicode: 'U+0128', title: 'LATIN CAPITAL LETTER I WITH TILDE' },
    { character: 'Ĵ', unicode: 'U+0134', title: 'LATIN CAPITAL LETTER J WITH CIRCUMFLEX' },
    { character: 'Ķ', unicode: 'U+0136', title: 'LATIN CAPITAL LETTER K WITH CEDILLA' },
    // { character: 'Ḳ', unicode: 'U+1E32', title: 'LATIN CAPITAL LETTER K WITH DOT BELOW' },
    // { character: 'Ƙ', unicode: 'U+0198', title: 'LATIN CAPITAL LETTER K WITH HOOK' },
    { character: 'Ĺ', unicode: 'U+0139', title: 'LATIN CAPITAL LETTER L WITH ACUTE' },
    { character: 'Ľ', unicode: 'U+013D', title: 'LATIN CAPITAL LETTER L WITH CARON' },
    { character: 'Ļ', unicode: 'U+013B', title: 'LATIN CAPITAL LETTER L WITH CEDILLA' },
    { character: 'Ŀ', unicode: 'U+013F', title: 'LATIN CAPITAL LETTER L WITH MIDDLE DOT' },
    { character: 'Ḷ', unicode: 'U+1E36', title: 'LATIN CAPITAL LETTER L WITH DOT BELOW' },
    { character: 'Ł', unicode: 'U+0141', title: 'LATIN CAPITAL LETTER L WITH STROKE' },
    { character: 'Ḿ', unicode: 'U+1E3E', title: 'LATIN CAPITAL LETTER M WITH ACUTE' },
    { character: 'Ṁ', unicode: 'U+1E40', title: 'LATIN CAPITAL LETTER M WITH DOT ABOVE' },
    { character: 'Ń', unicode: 'U+0143', title: 'LATIN CAPITAL LETTER N WITH ACUTE' },
    { character: 'Ň', unicode: 'U+0147', title: 'LATIN CAPITAL LETTER N WITH CARON' },
    { character: 'Ņ', unicode: 'U+0145', title: 'LATIN CAPITAL LETTER N WITH CEDILLA' },
    { character: 'Ṅ', unicode: 'U+1E44', title: 'LATIN CAPITAL LETTER N WITH DOT ABOVE' },
    { character: 'Ǹ', unicode: 'U+01F8', title: 'LATIN CAPITAL LETTER N WITH GRAVE' },
    { character: 'Ɲ', unicode: 'U+019D', title: 'LATIN CAPITAL LETTER N WITH LEFT HOOK' },
    { character: 'Ñ', unicode: 'U+00D1', title: 'LATIN CAPITAL LETTER N WITH TILDE' },
    { character: 'Ŋ', unicode: 'U+014A', title: 'LATIN CAPITAL LETTER ENG' },
    { character: 'Ó', unicode: 'U+00D3', title: 'LATIN CAPITAL LETTER O WITH ACUTE' },
    { character: 'Ŏ', unicode: 'U+014E', title: 'LATIN CAPITAL LETTER O WITH BREVE' },
    { character: 'Ǒ', unicode: 'U+01D1', title: 'LATIN CAPITAL LETTER O WITH CARON' },
    { character: 'Ô', unicode: 'U+00D4', title: 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX' },
    { character: 'Ö', unicode: 'U+00D6', title: 'LATIN CAPITAL LETTER O WITH DIAERESIS' },
    { character: 'Ọ', unicode: 'U+1ECC', title: 'LATIN CAPITAL LETTER O WITH DOT BELOW' },
    { character: 'Ò', unicode: 'U+00D2', title: 'LATIN CAPITAL LETTER O WITH GRAVE' },
    { character: 'Ő', unicode: 'U+0150', title: 'LATIN CAPITAL LETTER O WITH DOUBLE ACUTE' },
    { character: 'Ō', unicode: 'U+014C', title: 'LATIN CAPITAL LETTER O WITH MACRON' },
    { character: 'Ǫ', unicode: 'U+01EA', title: 'LATIN CAPITAL LETTER O WITH OGONEK' },
    { character: 'Ɔ', unicode: 'U+0186', title: 'LATIN CAPITAL LETTER OPEN O' },
    { character: 'Ø', unicode: 'U+00D8', title: 'LATIN CAPITAL LETTER O WITH STROKE' },
    { character: 'Ǿ', unicode: 'U+01FE', title: 'LATIN CAPITAL LETTER O WITH STROKE AND ACUTE' },
    { character: 'Õ', unicode: 'U+00D5', title: 'LATIN CAPITAL LETTER O WITH TILDE' },
    { character: 'Œ', unicode: 'U+0152', title: 'LATIN CAPITAL LIGATURE OE' },
    // { character: 'Ṗ', unicode: 'U+1E56', title: 'LATIN CAPITAL LETTER P WITH ACUTE' },
    { character: 'Þ', unicode: 'U+00DE', title: 'LATIN CAPITAL LETTER THORN' },
    { character: 'Ŕ', unicode: 'U+0154', title: 'LATIN CAPITAL LETTER R WITH ACUTE' },
    { character: 'Ř', unicode: 'U+0158', title: 'LATIN CAPITAL LETTER R WITH CARON' },
    { character: 'Ŗ', unicode: 'U+0156', title: 'LATIN CAPITAL LETTER R WITH CEDILLA' },
    { character: 'Ṛ', unicode: 'U+1E5A', title: 'LATIN CAPITAL LETTER R WITH DOT BELOW' },
    { character: 'Ś', unicode: 'U+015A', title: 'LATIN CAPITAL LETTER S WITH ACUTE' },
    { character: 'Š', unicode: 'U+0160', title: 'LATIN CAPITAL LETTER S WITH CARON' },
    { character: 'Ş', unicode: 'U+015E', title: 'LATIN CAPITAL LETTER S WITH CEDILLA' },
    { character: 'Ŝ', unicode: 'U+015C', title: 'LATIN CAPITAL LETTER S WITH CIRCUMFLEX' },
    { character: 'Ș', unicode: 'U+0218', title: 'LATIN CAPITAL LETTER S WITH COMMA BELOW' },
    // { character: 'Ṡ', unicode: 'U+1E60', title: 'LATIN CAPITAL LETTER S WITH DOT ABOVE' },
    // { character: 'Ṣ', unicode: 'U+1E62', title: 'LATIN CAPITAL LETTER S WITH DOT BELOW' },
    // { character: 'ẞ', unicode: 'U+1E9E', title: 'LATIN CAPITAL LETTER SHARP S' },
    { character: 'Ŧ', unicode: 'U+0166', title: 'LATIN CAPITAL LETTER T WITH STROKE' },
    { character: 'Ť', unicode: 'U+0164', title: 'LATIN CAPITAL LETTER T WITH CARON' },
    { character: 'Ţ', unicode: 'U+0162', title: 'LATIN CAPITAL LETTER T WITH CEDILLA' },
    { character: 'Ț', unicode: 'U+021A', title: 'LATIN CAPITAL LETTER T WITH COMMA BELOW' },
    { character: 'Ṫ', unicode: 'U+1E6A', title: 'LATIN CAPITAL LETTER T WITH DOT ABOVE' },
    { character: 'Ṭ', unicode: 'U+1E6C', title: 'LATIN CAPITAL LETTER T WITH DOT BELOW' },
    { character: 'Ú', unicode: 'U+00DA', title: 'LATIN CAPITAL LETTER U WITH ACUTE' },
    // { character: 'Ʉ', unicode: 'U+0244', title: 'LATIN CAPITAL LETTER U BAR' },
    { character: 'Ŭ', unicode: 'U+016C', title: 'LATIN CAPITAL LETTER U WITH BREVE' },
    // { character: 'Ǔ', unicode: 'U+01D3', title: 'LATIN CAPITAL LETTER U WITH CARON' },
    { character: 'Û', unicode: 'U+00DB', title: 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX' },
    { character: 'Ü', unicode: 'U+00DC', title: 'LATIN CAPITAL LETTER U WITH DIAERESIS' },
    { character: 'Ụ', unicode: 'U+1EE4', title: 'LATIN CAPITAL LETTER U WITH DOT BELOW' },
    { character: 'Ù', unicode: 'U+00D9', title: 'LATIN CAPITAL LETTER U WITH GRAVE' },
    { character: 'Ư', unicode: 'U+01AF', title: 'LATIN CAPITAL LETTER U WITH HORN' },
    { character: 'Ű', unicode: 'U+0170', title: 'LATIN CAPITAL LETTER U WITH DOUBLE ACUTE' },
    { character: 'Ū', unicode: 'U+016A', title: 'LATIN CAPITAL LETTER U WITH MACRON' },
    { character: 'Ų', unicode: 'U+0172', title: 'LATIN CAPITAL LETTER U WITH OGONEK' },
    { character: 'Ů', unicode: 'U+016E', title: 'LATIN CAPITAL LETTER U WITH RING ABOVE' },
    { character: 'Ũ', unicode: 'U+0168', title: 'LATIN CAPITAL LETTER U WITH TILDE' },
    // { character: 'Ɣ', unicode: 'U+0194', title: 'LATIN CAPITAL LETTER GAMMA' },
    // { character: 'Ʋ', unicode: 'U+01B2', title: 'LATIN CAPITAL LETTER V WITH HOOK' },
    { character: 'Ṽ', unicode: 'U+1E7C', title: 'LATIN CAPITAL LETTER V WITH TILDE' },
    { character: 'Ẃ', unicode: 'U+1E82', title: 'LATIN CAPITAL LETTER W WITH ACUTE' },
    { character: 'Ŵ', unicode: 'U+0174', title: 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX' },
    { character: 'Ẅ', unicode: 'U+1E84', title: 'LATIN CAPITAL LETTER W WITH DIAERESIS' },
    { character: 'Ẁ', unicode: 'U+1E80', title: 'LATIN CAPITAL LETTER W WITH GRAVE' },
    { character: 'Ý', unicode: 'U+00DD', title: 'LATIN CAPITAL LETTER Y WITH ACUTE' },
    { character: 'Ŷ', unicode: 'U+0176', title: 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX' },
    { character: 'Ÿ', unicode: 'U+0178', title: 'LATIN CAPITAL LETTER Y WITH DIAERESIS' },
    { character: 'Ẏ', unicode: 'U+1E8E', title: 'LATIN CAPITAL LETTER Y WITH DOT ABOVE' },
    { character: 'Ỳ', unicode: 'U+1EF2', title: 'LATIN CAPITAL LETTER Y WITH GRAVE' },
    // { character: 'Ƴ', unicode: 'U+01B3', title: 'LATIN CAPITAL LETTER Y WITH HOOK' },
    { character: 'Ȳ', unicode: 'U+0232', title: 'LATIN CAPITAL LETTER Y WITH MACRON' },
    { character: 'Ỹ', unicode: 'U+1EF8', title: 'LATIN CAPITAL LETTER Y WITH TILDE' },
    { character: 'Ź', unicode: 'U+0179', title: 'LATIN CAPITAL LETTER Z WITH ACUTE' },
    { character: 'Ž', unicode: 'U+017D', title: 'LATIN CAPITAL LETTER Z WITH CARON' },
    { character: 'Ż', unicode: 'U+017B', title: 'LATIN CAPITAL LETTER Z WITH DOT ABOVE' },
    { character: 'Ẓ', unicode: 'U+1E92', title: 'LATIN CAPITAL LETTER Z WITH DOT BELOW' },
    { character: 'á', unicode: 'U+00E1', title: 'LATIN SMALL LETTER A WITH ACUTE' },
    { character: 'ă', unicode: 'U+0103', title: 'LATIN SMALL LETTER A WITH BREVE' },
    // { character: 'ǎ', unicode: 'U+01CE', title: 'LATIN SMALL LETTER A WITH CARON' },
    { character: 'â', unicode: 'U+00E2', title: 'LATIN SMALL LETTER A WITH CIRCUMFLEX' },
    { character: 'ä', unicode: 'U+00E4', title: 'LATIN SMALL LETTER A WITH DIAERESIS' },
    { character: 'ạ', unicode: 'U+1EA1', title: 'LATIN SMALL LETTER A WITH DOT BELOW' },
    { character: 'à', unicode: 'U+00E0', title: 'LATIN SMALL LETTER A WITH GRAVE' },
    { character: 'ā', unicode: 'U+0101', title: 'LATIN SMALL LETTER A WITH MACRON' },
    // { character: 'ą', unicode: 'U+0105', title: 'LATIN SMALL LETTER A WITH OGONEK' },
    { character: 'å', unicode: 'U+00E5', title: 'LATIN SMALL LETTER A WITH RING ABOVE' },
    { character: 'ǻ', unicode: 'U+01FB', title: 'LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE' },
    { character: 'ã', unicode: 'U+00E3', title: 'LATIN SMALL LETTER A WITH TILDE' },
    { character: 'æ', unicode: 'U+00E6', title: 'LATIN SMALL LETTER AE' },
    { character: 'ǽ', unicode: 'U+01FD', title: 'LATIN SMALL LETTER AE WITH ACUTE' },
    // { character: 'ḃ', unicode: 'U+1E03', title: 'LATIN SMALL LETTER B WITH DOT ABOVE' },
    // { character: 'ɓ', unicode: 'U+0253', title: 'LATIN SMALL LETTER B WITH HOOK' },
    { character: 'ć', unicode: 'U+0107', title: 'LATIN SMALL LETTER C WITH ACUTE' },
    { character: 'č', unicode: 'U+010D', title: 'LATIN SMALL LETTER C WITH CARON' },
    { character: 'ç', unicode: 'U+00E7', title: 'LATIN SMALL LETTER C WITH CEDILLA' },
    { character: 'ĉ', unicode: 'U+0109', title: 'LATIN SMALL LETTER C WITH CIRCUMFLEX' },
    { character: 'ċ', unicode: 'U+010B', title: 'LATIN SMALL LETTER C WITH DOT ABOVE' },
    { character: 'ď', unicode: 'U+010F', title: 'LATIN SMALL LETTER D WITH CARON' },
    // { character: 'ḑ', unicode: 'U+1E11', title: 'LATIN SMALL LETTER D WITH CEDILLA' },
    { character: 'đ', unicode: 'U+0111', title: 'LATIN SMALL LETTER D WITH STROKE' },
    // { character: 'ḋ', unicode: 'U+1E0B', title: 'LATIN SMALL LETTER D WITH DOT ABOVE' },
    // { character: 'ḍ', unicode: 'U+1E0D', title: 'LATIN SMALL LETTER D WITH DOT BELOW' },
    // { character: 'ɗ', unicode: 'U+0257', title: 'LATIN SMALL LETTER D WITH HOOK' },
    // { character: 'ɖ', unicode: 'U+0256', title: 'LATIN SMALL LETTER D WITH TAIL' },
    // { character: 'ð', unicode: 'U+00F0', title: 'LATIN SMALL LETTER ETH' },
    { character: 'é', unicode: 'U+00E9', title: 'LATIN SMALL LETTER E WITH ACUTE' },
    { character: 'ĕ', unicode: 'U+0115', title: 'LATIN SMALL LETTER E WITH BREVE' },
    { character: 'ě', unicode: 'U+011B', title: 'LATIN SMALL LETTER E WITH CARON' },
    { character: 'ê', unicode: 'U+00EA', title: 'LATIN SMALL LETTER E WITH CIRCUMFLEX' },
    { character: 'ë', unicode: 'U+00EB', title: 'LATIN SMALL LETTER E WITH DIAERESIS' },
    { character: 'ė', unicode: 'U+0117', title: 'LATIN SMALL LETTER E WITH DOT ABOVE' },
    { character: 'ẹ', unicode: 'U+1EB9', title: 'LATIN SMALL LETTER E WITH DOT BELOW' },
    { character: 'è', unicode: 'U+00E8', title: 'LATIN SMALL LETTER E WITH GRAVE' },
    { character: 'ē', unicode: 'U+0113', title: 'LATIN SMALL LETTER E WITH MACRON' },
    { character: 'ę', unicode: 'U+0119', title: 'LATIN SMALL LETTER E WITH OGONEK' },
    // { character: 'ɛ', unicode: 'U+025B', title: 'LATIN SMALL LETTER OPEN E' },
    { character: 'ẽ', unicode: 'U+1EBD', title: 'LATIN SMALL LETTER E WITH TILDE' },
    { character: 'ǝ', unicode: 'U+01DD', title: 'LATIN SMALL LETTER TURNED E' },
    { character: 'ə', unicode: 'U+0259', title: 'LATIN SMALL LETTER SCHWA' },
    // { character: 'ḟ', unicode: 'U+1E1F', title: 'LATIN SMALL LETTER F WITH DOT ABOVE' },
    // { character: 'ɣ', unicode: 'U+0263', title: 'LATIN SMALL LETTER GAMMA' },
    { character: 'ğ', unicode: 'U+011F', title: 'LATIN SMALL LETTER G WITH BREVE' },
    { character: 'ǧ', unicode: 'U+01E7', title: 'LATIN SMALL LETTER G WITH CARON' },
    { character: 'ĝ', unicode: 'U+011D', title: 'LATIN SMALL LETTER G WITH CIRCUMFLEX' },
    { character: 'ģ', unicode: 'U+0123', title: 'LATIN SMALL LETTER G WITH CEDILLA' },
    { character: 'ġ', unicode: 'U+0121', title: 'LATIN SMALL LETTER G WITH DOT ABOVE' },
    { character: 'ɠ', unicode: 'U+0260', title: 'LATIN SMALL LETTER G WITH HOOK' },
    // { character: 'ʔ', unicode: 'U+0294', title: 'LATIN LETTER GLOTTAL STOP' },
    // { character: 'ḡ', unicode: 'U+1E21', title: 'LATIN SMALL LETTER G WITH MACRON' },
    { character: 'ħ', unicode: 'U+0127', title: 'LATIN SMALL LETTER H WITH STROKE' },
    // { character: 'ḫ', unicode: 'U+1E2B', title: 'LATIN SMALL LETTER H WITH BREVE BELOW' },
    // { character: 'ȟ', unicode: 'U+021F', title: 'LATIN SMALL LETTER H WITH CARON' },
    { character: 'ĥ', unicode: 'U+0125', title: 'LATIN SMALL LETTER H WITH CIRCUMFLEX' },
    // { character: 'ḥ', unicode: 'U+1E25', title: 'LATIN SMALL LETTER H WITH DOT BELOW' },
    { character: 'ı', unicode: 'U+0131', title: 'LATIN SMALL LETTER DOTLESS I' },
    { character: 'í', unicode: 'U+00ED', title: 'LATIN SMALL LETTER I WITH ACUTE' },
    { character: 'ĭ', unicode: 'U+012D', title: 'LATIN SMALL LETTER I WITH BREVE' },
    // { character: 'ǐ', unicode: 'U+01D0', title: 'LATIN SMALL LETTER I WITH CARON' },
    { character: 'î', unicode: 'U+00EE', title: 'LATIN SMALL LETTER I WITH CIRCUMFLEX' },
    { character: 'ï', unicode: 'U+00EF', title: 'LATIN SMALL LETTER I WITH DIAERESIS' },
    { character: 'ị', unicode: 'U+1ECB', title: 'LATIN SMALL LETTER I WITH DOT BELOW' },
    { character: 'ì', unicode: 'U+00EC', title: 'LATIN SMALL LETTER I WITH GRAVE' },
    { character: 'ī', unicode: 'U+012B', title: 'LATIN SMALL LETTER I WITH MACRON' },
    { character: 'į', unicode: 'U+012F', title: 'LATIN SMALL LETTER I WITH OGONEK' },
    // { character: 'ɨ', unicode: 'U+0268', title: 'LATIN SMALL LETTER I WITH STROKE' },
    { character: 'ĩ', unicode: 'U+0129', title: 'LATIN SMALL LETTER I WITH TILDE' },
    { character: 'ĳ', unicode: 'U+0133', title: 'LATIN SMALL LIGATURE IJ' },
    { character: 'ȷ', unicode: 'U+0237', title: 'LATIN SMALL LETTER DOTLESS J' },
    { character: 'ĵ', unicode: 'U+0135', title: 'LATIN SMALL LETTER J WITH CIRCUMFLEX' },
    { character: 'ķ', unicode: 'U+0137', title: 'LATIN SMALL LETTER K WITH CEDILLA' },
    { character: 'ḳ', unicode: 'U+1E33', title: 'LATIN SMALL LETTER K WITH DOT BELOW' },
    // { character: 'ĸ', unicode: 'U+0138', title: 'LATIN SMALL LETTER KRA' },
    // { character: 'ƙ', unicode: 'U+0199', title: 'LATIN SMALL LETTER K WITH HOOK' },
    // { character: 'ĺ', unicode: 'U+013A', title: 'LATIN SMALL LETTER L WITH ACUTE' },
    { character: 'ľ', unicode: 'U+013E', title: 'LATIN SMALL LETTER L WITH CARON' },
    { character: 'ļ', unicode: 'U+013C', title: 'LATIN SMALL LETTER L WITH CEDILLA' },
    // { character: 'ŀ', unicode: 'U+0140', title: 'LATIN SMALL LETTER L WITH MIDDLE DOT' },
    // { character: 'ḷ', unicode: 'U+1E37', title: 'LATIN SMALL LETTER L WITH DOT BELOW' },
    // { character: 'ẛ', unicode: 'U+1E9B', title: 'LATIN SMALL LETTER LONG S WITH DOT ABOVE' },
    { character: 'ł', unicode: 'U+0142', title: 'LATIN SMALL LETTER L WITH STROKE' },
    // { character: 'ḿ', unicode: 'U+1E3F', title: 'LATIN SMALL LETTER M WITH ACUTE' },
    // { character: 'ṁ', unicode: 'U+1E41', title: 'LATIN SMALL LETTER M WITH DOT ABOVE' },
    { character: 'ń', unicode: 'U+0144', title: 'LATIN SMALL LETTER N WITH ACUTE' },
    { character: 'ň', unicode: 'U+0148', title: 'LATIN SMALL LETTER N WITH CARON' },
    { character: 'ņ', unicode: 'U+0146', title: 'LATIN SMALL LETTER N WITH CEDILLA' },
    { character: 'ṅ', unicode: 'U+1E45', title: 'LATIN SMALL LETTER N WITH DOT ABOVE' },
    { character: 'ǹ', unicode: 'U+01F9', title: 'LATIN SMALL LETTER N WITH GRAVE' },
    { character: 'ɲ', unicode: 'U+0272', title: 'LATIN SMALL LETTER N WITH LEFT HOOK' },
    { character: 'ñ', unicode: 'U+00F1', title: 'LATIN SMALL LETTER N WITH TILDE' },
    { character: 'ŋ', unicode: 'U+014B', title: 'LATIN SMALL LETTER ENG' },
    { character: 'ó', unicode: 'U+00F3', title: 'LATIN SMALL LETTER O WITH ACUTE' },
    // { character: 'ŏ', unicode: 'U+014F', title: 'LATIN SMALL LETTER O WITH BREVE' },
    // { character: 'ǒ', unicode: 'U+01D2', title: 'LATIN SMALL LETTER O WITH CARON' },
    { character: 'ô', unicode: 'U+00F4', title: 'LATIN SMALL LETTER O WITH CIRCUMFLEX' },
    { character: 'ö', unicode: 'U+00F6', title: 'LATIN SMALL LETTER O WITH DIAERESIS' },
    { character: 'ọ', unicode: 'U+1ECD', title: 'LATIN SMALL LETTER O WITH DOT BELOW' },
    { character: 'ò', unicode: 'U+00F2', title: 'LATIN SMALL LETTER O WITH GRAVE' },
    { character: 'ő', unicode: 'U+0151', title: 'LATIN SMALL LETTER O WITH DOUBLE ACUTE' },
    { character: 'ō', unicode: 'U+014D', title: 'LATIN SMALL LETTER O WITH MACRON' },
    { character: 'ǫ', unicode: 'U+01EB', title: 'LATIN SMALL LETTER O WITH OGONEK' },
    { character: 'ɔ', unicode: 'U+0254', title: 'LATIN SMALL LETTER OPEN O' },
    { character: 'ø', unicode: 'U+00F8', title: 'LATIN SMALL LETTER O WITH STROKE' },
    { character: 'ǿ', unicode: 'U+01FF', title: 'LATIN SMALL LETTER O WITH STROKE AND ACUTE' },
    { character: 'õ', unicode: 'U+00F5', title: 'LATIN SMALL LETTER O WITH TILDE' },
    { character: 'œ', unicode: 'U+0153', title: 'LATIN SMALL LIGATURE OE' },
    // { character: 'ṗ', unicode: 'U+1E57', title: 'LATIN SMALL LETTER P WITH ACUTE' },
    { character: 'þ', unicode: 'U+00FE', title: 'LATIN SMALL LETTER THORN' },
    { character: 'ŕ', unicode: 'U+0155', title: 'LATIN SMALL LETTER R WITH ACUTE' },
    { character: 'ř', unicode: 'U+0159', title: 'LATIN SMALL LETTER R WITH CARON' },
    { character: 'ŗ', unicode: 'U+0157', title: 'LATIN SMALL LETTER R WITH CEDILLA' },
    // { character: 'ṛ', unicode: 'U+1E5B', title: 'LATIN SMALL LETTER R WITH DOT BELOW' },
    { character: 'ɼ', unicode: 'U+027C', title: 'LATIN SMALL LETTER R WITH LONG LEG' },
    { character: 'ś', unicode: 'U+015B', title: 'LATIN SMALL LETTER S WITH ACUTE' },
    { character: 'š', unicode: 'U+0161', title: 'LATIN SMALL LETTER S WITH CARON' },
    { character: 'ş', unicode: 'U+015F', title: 'LATIN SMALL LETTER S WITH CEDILLA' },
    { character: 'ŝ', unicode: 'U+015D', title: 'LATIN SMALL LETTER S WITH CIRCUMFLEX' },
    { character: 'ș', unicode: 'U+0219', title: 'LATIN SMALL LETTER S WITH COMMA BELOW' },
    // { character: 'ṡ', unicode: 'U+1E61', title: 'LATIN SMALL LETTER S WITH DOT ABOVE' },
    // { character: 'ṣ', unicode: 'U+1E63', title: 'LATIN SMALL LETTER S WITH DOT BELOW' },
    // { character: 'ß', unicode: 'U+00DF', title: 'LATIN SMALL LETTER SHARP S' },
    // { character: 'ſ', unicode: 'U+017F', title: 'LATIN SMALL LETTER LONG S' },
    { character: 'ŧ', unicode: 'U+0167', title: 'LATIN SMALL LETTER T WITH STROKE' },
    // { character: 'ť', unicode: 'U+0165', title: 'LATIN SMALL LETTER T WITH CARON' },
    { character: 'ţ', unicode: 'U+0163', title: 'LATIN SMALL LETTER T WITH CEDILLA' },
    // { character: 'ț', unicode: 'U+021B', title: 'LATIN SMALL LETTER T WITH COMMA BELOW' },
    // { character: 'ṫ', unicode: 'U+1E6B', title: 'LATIN SMALL LETTER T WITH DOT ABOVE' },
    // { character: 'ṭ', unicode: 'U+1E6D', title: 'LATIN SMALL LETTER T WITH DOT BELOW' },
    { character: 'ú', unicode: 'U+00FA', title: 'LATIN SMALL LETTER U WITH ACUTE' },
    // { character: 'ʉ', unicode: 'U+0289', title: 'LATIN SMALL LETTER U BAR' },
    { character: 'ŭ', unicode: 'U+016D', title: 'LATIN SMALL LETTER U WITH BREVE' },
    { character: 'ǔ', unicode: 'U+01D4', title: 'LATIN SMALL LETTER U WITH CARON' },
    { character: 'û', unicode: 'U+00FB', title: 'LATIN SMALL LETTER U WITH CIRCUMFLEX' },
    { character: 'ü', unicode: 'U+00FC', title: 'LATIN SMALL LETTER U WITH DIAERESIS' },
    { character: 'ụ', unicode: 'U+1EE5', title: 'LATIN SMALL LETTER U WITH DOT BELOW' },
    { character: 'ù', unicode: 'U+00F9', title: 'LATIN SMALL LETTER U WITH GRAVE' },
    // { character: 'ư', unicode: 'U+01B0', title: 'LATIN SMALL LETTER U WITH HORN' },
    { character: 'ű', unicode: 'U+0171', title: 'LATIN SMALL LETTER U WITH DOUBLE ACUTE' },
    { character: 'ū', unicode: 'U+016B', title: 'LATIN SMALL LETTER U WITH MACRON' },
    { character: 'ų', unicode: 'U+0173', title: 'LATIN SMALL LETTER U WITH OGONEK' },
    { character: 'ů', unicode: 'U+016F', title: 'LATIN SMALL LETTER U WITH RING ABOVE' },
    { character: 'ũ', unicode: 'U+0169', title: 'LATIN SMALL LETTER U WITH TILDE' },
    // { character: 'ʋ', unicode: 'U+028B', title: 'LATIN SMALL LETTER V WITH HOOK' },
    // { character: 'ṽ', unicode: 'U+1E7D', title: 'LATIN SMALL LETTER V WITH TILDE' },
    { character: 'ẃ', unicode: 'U+1E83', title: 'LATIN SMALL LETTER W WITH ACUTE' },
    { character: 'ŵ', unicode: 'U+0175', title: 'LATIN SMALL LETTER W WITH CIRCUMFLEX' },
    { character: 'ẅ', unicode: 'U+1E85', title: 'LATIN SMALL LETTER W WITH DIAERESIS' },
    { character: 'ẁ', unicode: 'U+1E81', title: 'LATIN SMALL LETTER W WITH GRAVE' },
    { character: 'ý', unicode: 'U+00FD', title: 'LATIN SMALL LETTER Y WITH ACUTE' },
    { character: 'ŷ', unicode: 'U+0177', title: 'LATIN SMALL LETTER Y WITH CIRCUMFLEX' },
    { character: 'ÿ', unicode: 'U+00FF', title: 'LATIN SMALL LETTER Y WITH DIAERESIS' },
    { character: 'ẏ', unicode: 'U+1E8F', title: 'LATIN SMALL LETTER Y WITH DOT ABOVE' },
    { character: 'ỳ', unicode: 'U+1EF3', title: 'LATIN SMALL LETTER Y WITH GRAVE' },
    { character: 'ƴ', unicode: 'U+01B4', title: 'LATIN SMALL LETTER Y WITH HOOK' },
    { character: 'ȳ', unicode: 'U+0233', title: 'LATIN SMALL LETTER Y WITH MACRON' },
    { character: 'ỹ', unicode: 'U+1EF9', title: 'LATIN SMALL LETTER Y WITH TILDE' },
    { character: 'ź', unicode: 'U+017A', title: 'LATIN SMALL LETTER Z WITH ACUTE' },
    { character: 'ž', unicode: 'U+017E', title: 'LATIN SMALL LETTER Z WITH CARON' },
    { character: 'ż', unicode: 'U+017C', title: 'LATIN SMALL LETTER Z WITH DOT ABOVE' },
    { character: 'ẓ', unicode: 'U+1E93', title: 'LATIN SMALL LETTER Z WITH DOT BELOW' },
    // ... Add remaining extended Latin characters ...
  ],
  // greekLetters: [
  //   { character: 'Α', unicode: 'U+0391', title: 'GREEK CAPITAL LETTER ALPHA' },
  //   { character: 'Β', unicode: 'U+0392', title: 'GREEK CAPITAL LETTER BETA' },
  //   // ... Add remaining Greek letters ...
  // ],
  symbols: [
    { character: '@', unicode: 'U+0040', title: 'COMMERCIAL AT' },
    { character: '&', unicode: 'U+0026', title: 'AMPERSAND' },
    { character: '.', unicode: 'U+002E', title: 'FULL STOP' },
    { character: ',', unicode: 'U+002C', title: 'COMMA' },
    { character: ':', unicode: 'U+003A', title: 'COLON' },
    { character: ';', unicode: 'U+003B', title: 'SEMICOLON' },
    { character: '…', unicode: 'U+2026', title: 'HORIZONTAL ELLIPSIS' },
    { character: '!', unicode: 'U+0021', title: 'EXCLAMATION MARK' },
    { character: '¡', unicode: 'U+00A1', title: 'INVERTED EXCLAMATION MARK' },
    { character: '?', unicode: 'U+003F', title: 'QUESTION MARK' },
    { character: '¿', unicode: 'U+00BF', title: 'INVERTED QUESTION MARK' },
    { character: '·', unicode: 'U+00B7', title: 'MIDDLE DOT' },
    { character: '•', unicode: 'U+2022', title: 'BULLET' },
    { character: '*', unicode: 'U+002A', title: 'ASTERISK' },
    { character: '⁊', unicode: 'U+204A', title: 'TIRONIAN SIGN ET' },
    { character: '‧', unicode: 'U+2027', title: 'HYPHENATION POINT' },
    { character: '#', unicode: 'U+0023', title: 'NUMBER SIGN' },
    { character: '/', unicode: 'U+002F', title: 'SOLIDUS' },
    { character: '\\', unicode: 'U+005C', title: 'REVERSE SOLIDUS' },
    { character: '-', unicode: 'U+002D', title: 'HYPHEN-MINUS' },
    { character: '–', unicode: 'U+2013', title: 'EN DASH' },
    { character: '—', unicode: 'U+2014', title: 'EM DASH' },
    // { character: '⸗', unicode: 'U+2E17', title: 'DOUBLE OBLIQUE HYPHEN' },
    { character: '_', unicode: 'U+005F', title: 'LOW LINE' },
    { character: '(', unicode: 'U+0028', title: 'LEFT PARENTHESIS' },
    { character: ')', unicode: 'U+0029', title: 'RIGHT PARENTHESIS' },
    { character: '{', unicode: 'U+007B', title: 'LEFT CURLY BRACKET' },
    { character: '}', unicode: 'U+007D', title: 'RIGHT CURLY BRACKET' },
    { character: '[', unicode: 'U+005B', title: 'LEFT SQUARE BRACKET' },
    { character: ']', unicode: 'U+005D', title: 'RIGHT SQUARE BRACKET' },
    { character: '‚', unicode: 'U+201A', title: 'SINGLE LOW-9 QUOTATION MARK' },
    { character: '„', unicode: 'U+201E', title: 'DOUBLE LOW-9 QUOTATION MARK' },
    { character: '“', unicode: 'U+201C', title: 'LEFT DOUBLE QUOTATION MARK' },
    { character: '”', unicode: 'U+201D', title: 'RIGHT DOUBLE QUOTATION MARK' },
    { character: '‘', unicode: 'U+2018', title: 'LEFT SINGLE QUOTATION MARK' },
    { character: '’', unicode: 'U+2019', title: 'RIGHT SINGLE QUOTATION MARK' },
    { character: '«', unicode: 'U+00AB', title: 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK' },
    { character: '»', unicode: 'U+00BB', title: 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK' },
    // { character: '‹', unicode: 'U+2039', title: 'SINGLE LEFT-POINTING ANGLE QUOTATION MARK' },
    // { character: '›', unicode: 'U+203A', title: 'SINGLE RIGHT-POINTING ANGLE QUOTATION MARK' },
    { character: '"', unicode: 'U+0022', title: 'QUOTATION MARK' },
    { character: "'", unicode: 'U+0027', title: 'APOSTROPHE' },
    // { character: '⟨', unicode: 'U+27E8', title: 'MATHEMATICAL LEFT ANGLE BRACKET' },
    // { character: '⟩', unicode: 'U+27E9', title: 'MATHEMATICAL RIGHT ANGLE BRACKET' },
    // { character: 'ª', unicode: 'U+00AA', title: 'FEMININE ORDINAL INDICATOR' },
    // { character: 'º', unicode: 'U+00BA', title: 'MASCULINE ORDINAL INDICATOR' },
    // { character: 'ǂ', unicode: 'U+01C2', title: 'LATIN LETTER ALVEOLAR CLICK' },
    // { character: 'ǀ', unicode: 'U+01C0', title: 'LATIN LETTER DENTAL CLICK' },
    // { character: 'ǁ', unicode: 'U+01C1', title: 'LATIN LETTER LATERAL CLICK' },
    // { character: 'ǃ', unicode: 'U+01C3', title: 'LATIN LETTER RETROFLEX CLICK' },
    { character: '¶', unicode: 'U+00B6', title: 'PILCROW SIGN' },
    { character: '§', unicode: 'U+00A7', title: 'SECTION SIGN' },
    { character: '©', unicode: 'U+00A9', title: 'COPYRIGHT SIGN' },
    { character: '®', unicode: 'U+00AE', title: 'REGISTERED SIGN' },
    // { character: '™', unicode: 'U+2122', title: 'TRADE MARK SIGN' },
    { character: '°', unicode: 'U+00B0', title: 'DEGREE SIGN' },
    { character: '′', unicode: 'U+2032', title: 'PRIME' },
    { character: '″', unicode: 'U+2033', title: 'DOUBLE PRIME' },
    { character: '|', unicode: 'U+007C', title: 'VERTICAL LINE' },
    { character: '¦', unicode: 'U+00A6', title: 'BROKEN BAR' },
    { character: '†', unicode: 'U+2020', title: 'DAGGER' },
    { character: '‡', unicode: 'U+2021', title: 'DOUBLE DAGGER' },
    // { character: '⌥', unicode: 'U+2325', title: 'OPTION KEY' },
    // { character: '⌘', unicode: 'U+2318', title: 'PLACE OF INTEREST SIGN' },
  ],
  numeralsMathCurrency: [
    { character: '0', unicode: 'U+0030', title: 'DIGIT ZERO' },
    { character: '1', unicode: 'U+0031', title: 'DIGIT ONE' },
    { character: '2', unicode: 'U+0032', title: 'DIGIT TWO' },
    { character: '3', unicode: 'U+0033', title: 'DIGIT THREE' },
    { character: '4', unicode: 'U+0034', title: 'DIGIT FOUR' },
    { character: '5', unicode: 'U+0035', title: 'DIGIT FIVE' },
    { character: '6', unicode: 'U+0036', title: 'DIGIT SIX' },
    { character: '7', unicode: 'U+0037', title: 'DIGIT SEVEN' },
    { character: '8', unicode: 'U+0038', title: 'DIGIT EIGHT' },
    { character: '9', unicode: 'U+0039', title: 'DIGIT NINE' },
    // { character: '⁰', unicode: 'U+2070', title: 'SUPERSCRIPT ZERO' },
    // { character: '¹', unicode: 'U+00B9', title: 'SUPERSCRIPT ONE' },
    // { character: '²', unicode: 'U+00B2', title: 'SUPERSCRIPT TWO' },
    // { character: '³', unicode: 'U+00B3', title: 'SUPERSCRIPT THREE' },
    // { character: '⁴', unicode: 'U+2074', title: 'SUPERSCRIPT FOUR' },
    // { character: '⁵', unicode: 'U+2075', title: 'SUPERSCRIPT FIVE' },
    // { character: '⁶', unicode: 'U+2076', title: 'SUPERSCRIPT SIX' },
    // { character: '⁷', unicode: 'U+2077', title: 'SUPERSCRIPT SEVEN' },
    // { character: '⁸', unicode: 'U+2078', title: 'SUPERSCRIPT EIGHT' },
    // { character: '⁹', unicode: 'U+2079', title: 'SUPERSCRIPT NINE' },
    // { character: '₀', unicode: 'U+2080', title: 'SUBSCRIPT ZERO' },
    // { character: '₁', unicode: 'U+2081', title: 'SUBSCRIPT ONE' },
    // { character: '₂', unicode: 'U+2082', title: 'SUBSCRIPT TWO' },
    // { character: '₃', unicode: 'U+2083', title: 'SUBSCRIPT THREE' },
    // { character: '₄', unicode: 'U+2084', title: 'SUBSCRIPT FOUR' },
    // { character: '₅', unicode: 'U+2085', title: 'SUBSCRIPT FIVE' },
    // { character: '₆', unicode: 'U+2086', title: 'SUBSCRIPT SIX' },
    // { character: '₇', unicode: 'U+2087', title: 'SUBSCRIPT SEVEN' },
    // { character: '₈', unicode: 'U+2088', title: 'SUBSCRIPT EIGHT' },
    // { character: '₉', unicode: 'U+2089', title: 'SUBSCRIPT NINE' },
    // { character: 'ƒ', unicode: 'U+0192', title: 'LATIN SMALL LETTER F WITH HOOK' },
    // { character: '฿', unicode: 'U+0E3F', title: 'THAI CURRENCY SYMBOL BAHT' },
    // { character: '₿', unicode: 'U+20BF', title: 'BITCOIN SIGN' },
    { character: '¢', unicode: 'U+00A2', title: 'CENT SIGN' },
    // { character: '¤', unicode: 'U+00A4', title: 'CURRENCY SIGN' },
    { character: '$', unicode: 'U+0024', title: 'DOLLAR SIGN' },
    // { character: '€', unicode: 'U+20AC', title: 'EURO SIGN' },
    // { character: '₣', unicode: 'U+20A3', title: 'FRENCH FRANC SIGN' },
    // { character: '₴', unicode: 'U+20B4', title: 'UKRAINIAN HRYVNIA SIGN' },
    // { character: '₺', unicode: 'U+20BA', title: 'TURKISH LIRA SIGN' },
    // { character: '₽', unicode: 'U+20BD', title: 'RUBLE SIGN' },
    // { character: '₹', unicode: 'U+20B9', title: 'INDIAN RUPEE SIGN' },
    // { character: '₪', unicode: 'U+20AA', title: 'NEW SHEQEL SIGN' },
    // { character: '£', unicode: 'U+00A3', title: 'POUND SIGN' },
    // { character: '₸', unicode: 'U+20B8', title: 'KAZAKHSTANI TENGE SIGN' },
    // { character: '₮', unicode: 'U+20AE', title: 'TUGRIK SIGN' },
    // { character: '₩', unicode: 'U+20A9', title: 'WON SIGN' },
    { character: '¥', unicode: 'U+00A5', title: 'YEN SIGN' },
    { character: '+', unicode: 'U+002B', title: 'PLUS SIGN' },
    { character: '−', unicode: 'U+2212', title: 'MINUS SIGN' },
    { character: '×', unicode: 'U+00D7', title: 'MULTIPLICATION SIGN' },
    { character: '÷', unicode: 'U+00F7', title: 'DIVISION SIGN' },
    { character: '=', unicode: 'U+003D', title: 'EQUALS SIGN' },
    { character: '≠', unicode: 'U+2260', title: 'NOT EQUAL TO' },
    { character: '>', unicode: 'U+003E', title: 'GREATER-THAN SIGN' },
    { character: '<', unicode: 'U+003C', title: 'LESS-THAN SIGN' },
    { character: '≥', unicode: 'U+2265', title: 'GREATER-THAN OR EQUAL TO' },
    { character: '≤', unicode: 'U+2264', title: 'LESS-THAN OR EQUAL TO' },
    { character: '±', unicode: 'U+00B1', title: 'PLUS-MINUS SIGN' },
    { character: '≈', unicode: 'U+2248', title: 'ALMOST EQUAL TO' },
    { character: '~', unicode: 'U+007E', title: 'TILDE' },
    { character: '¬', unicode: 'U+00AC', title: 'NOT SIGN' },
    { character: '^', unicode: 'U+005E', title: 'CIRCUMFLEX ACCENT' },
    // { character: '∞', unicode: 'U+221E', title: 'INFINITY' },
    // { character: '∫', unicode: 'U+222B', title: 'INTEGRAL' },
    // { character: 'Ω', unicode: 'U+2126', title: 'OHM SIGN' },
    // { character: '∆', unicode: 'U+2206', title: 'INCREMENT' },
    // { character: '∏', unicode: 'U+220F', title: 'N-ARY PRODUCT' },
    // { character: '∑', unicode: 'U+2211', title: 'N-ARY SUMMATION' },
    // { character: '√', unicode: 'U+221A', title: 'SQUARE ROOT' },
    // { character: '∂', unicode: 'U+2202', title: 'PARTIAL DIFFERENTIAL' },
    // { character: 'µ', unicode: 'U+00B5', title: 'MICRO SIGN' },
    { character: '%', unicode: 'U+0025', title: 'PERCENT SIGN' },
    // { character: '‰', unicode: 'U+2030', title: 'PER MILLE SIGN' },
    // { character: '⁒', unicode: 'U+2052', title: 'COMMERCIAL MINUS SIGN' },
    // { character: '⁄', unicode: 'U+2044', title: 'FRACTION SLASH' },
    // { character: '½', unicode: 'U+00BD', title: 'VULGAR FRACTION ONE HALF' },
    // { character: '¼', unicode: 'U+00BC', title: 'VULGAR FRACTION ONE QUARTER' },
    // { character: '¾', unicode: 'U+00BE', title: 'VULGAR FRACTION THREE QUARTERS' },
    // { character: '⅛', unicode: 'U+215B', title: 'VULGAR FRACTION ONE EIGHTH' },
    // { character: '⅜', unicode: 'U+215C', title: 'VULGAR FRACTION THREE EIGHTHS' },
    // { character: '⅝', unicode: 'U+215D', title: 'VULGAR FRACTION FIVE EIGHTHS' },
    // { character: '⅞', unicode: 'U+215E', title: 'VULGAR FRACTION SEVEN EIGHTHS' },
    // { character: 'ℓ', unicode: 'U+2113', title: 'SCRIPT SMALL L' },
    // { character: '℮', unicode: 'U+212E', title: 'ESTIMATED SYMBOL' }
  ],
}

export default function CharacterViewer() {
  // State to track the character displayed in the circle
  const [hoveredChar, setHoveredChar] = useState(characterSets.basicLatin[0]) // Default character

  return (
    <div className="my-auto p-6">
      {/* Section Header */}
      <div className="mb-8 text-center" style={{ fontFamily: 'Euripides' }}></div>

      <div className="grid w-full grid-cols-2">
        {/* Circle Element (Left Column - Sticky) */}
        <div className="sticky top-7 h-min">
          <div
            className="my-2 flex items-center justify-center rounded-full text-sm font-bold leading-none text-white"
            style={{ fontFamily: 'Euripides' }}
          >
            {hoveredChar.unicode}
          </div>
          <div
            className="flex items-center justify-center rounded-full text-sm font-bold leading-none text-white"
            style={{ fontFamily: 'Euripides' }}
          >
            {hoveredChar.title}
          </div>
          <div
            className="mx-10 my-10 flex items-center justify-center rounded-full py-16 text-[250px] font-bold leading-none text-white"
            style={{ fontFamily: 'Euripides' }}
          >
            {hoveredChar.character}
          </div>
        </div>

        {/* Characters Display (Right Column) */}
        <div className="mb-16">
          {/* Render Character Sets */}
          {Object.keys(characterSets).map((setName) => (
            <div key={setName}>
              <h3 className="mt-8">{setName.replace(/([A-Z])/g, ' $1')}</h3>
              <div className="grid grid-flow-row-dense grid-cols-10">
                {characterSets[setName].map(({ character, unicode, title }) => (
                  <div
                    key={unicode}
                    className="relative my-4 cursor-pointer text-center text-3xl hover:bg-gray-200"
                    style={{
                      fontFamily: 'Euripides',
                      width: '48px',
                      height: '48px',
                      lineHeight: '48px',
                    }}
                    onMouseEnter={() => setHoveredChar({ character, unicode, title })}
                  >
                    {character}
                    {/* Hover effect with absolutely positioned border */}
                    <div className="absolute inset-0 hidden rounded-full border-2 border-dotted hover:block"></div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
